<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Anshuls-MacBook.local" ignored="1" name="Sample Test Case for Package" tests="30" failures="7" timestamp="2022-06-14T19:50:33 IST" time="0.155" errors="0">
  <testcase name="sampleTestTwoMethodOne" time="0.002" classname="com.testng.training.SamplClassTwo"/>
  <testcase name="sampleTestTwoMethodTwo" time="0.002" classname="com.testng.training.SamplClassTwo"/>
  <testcase name="testFive" time="0.002" classname="com.testng.training.AssertionExample"/>
  <testcase name="testFour" time="0.006" classname="com.testng.training.AssertionExample">
    <failure type="java.lang.AssertionError" message="Making Test Failure expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Making Test Failure expected [true] but found [false]
at com.testng.training.AssertionExample.testFour(AssertionExample.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testFour -->
  <testcase name="testOne" time="0.002" classname="com.testng.training.AssertionExample"/>
  <testcase name="testSix" time="0.001" classname="com.testng.training.AssertionExample"/>
  <testcase name="testThree" time="0.002" classname="com.testng.training.AssertionExample"/>
  <testcase name="testTwo" time="0.001" classname="com.testng.training.AssertionExample">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at com.testng.training.AssertionExample.testTwo(AssertionExample.java:17)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testTwo -->
  <testcase name="testOne" time="0.003" classname="com.testng.training.PriorityExample"/>
  <testcase name="testTwo" time="0.001" classname="com.testng.training.PriorityExample"/>
  <testcase name="testThree" time="0.0" classname="com.testng.training.PriorityExample"/>
  <testcase name="testFour" time="0.001" classname="com.testng.training.PriorityExample"/>
  <testcase name="testCaseOne" time="0.0" classname="com.testng.training.TestParameters">
    <failure type="org.testng.TestNGException" message="
Parameter &amp;apos;browser&amp;apos; is required by @Test on method testCaseOne but has not been marked @Optional or defined
in /Users/anshul/JavaTraining/MyTestNGProject/testng.xml">
      <![CDATA[org.testng.TestNGException: 
Parameter 'browser' is required by @Test on method testCaseOne but has not been marked @Optional or defined
in /Users/anshul/JavaTraining/MyTestNGProject/testng.xml
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testCaseOne -->
  <testcase name="testCaseTwo" time="0.0" classname="com.testng.training.TestParameters">
    <failure type="org.testng.TestNGException" message="
Parameter &amp;apos;userName&amp;apos; is required by @Test on method testCaseTwo but has not been marked @Optional or defined
in /Users/anshul/JavaTraining/MyTestNGProject/testng.xml">
      <![CDATA[org.testng.TestNGException: 
Parameter 'userName' is required by @Test on method testCaseTwo but has not been marked @Optional or defined
in /Users/anshul/JavaTraining/MyTestNGProject/testng.xml
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testCaseTwo -->
  <testcase name="testFour" time="0.001" classname="com.testng.training.SkippingExample"/>
  <testcase name="testOne" time="0.001" classname="com.testng.training.SkippingExample"/>
  <testcase name="testThree" time="0.001" classname="com.testng.training.SkippingExample">
    <skipped/>
  </testcase> <!-- testThree -->
  <testcase name="start" time="0.002" classname="com.testng.training.MultiTestDependency"/>
  <testcase name="init" time="0.001" classname="com.testng.training.MultiTestDependency"/>
  <testcase name="process" time="0.001" classname="com.testng.training.MultiTestDependency">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testng.training.MultiTestDependency.process(MultiTestDependency.java:21)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- process -->
  <testcase name="stop" time="0.005" classname="com.testng.training.MultiTestDependency">
    <skipped/>
  </testcase> <!-- stop -->
  <testcase name="testCaseFour" time="0.001" classname="com.testng.training.TestCaseGrouping"/>
  <testcase name="testCaseOne" time="0.001" classname="com.testng.training.TestCaseGrouping"/>
  <testcase name="testCaseThree" time="0.001" classname="com.testng.training.TestCaseGrouping"/>
  <testcase name="testCaseTwo" time="0.001" classname="com.testng.training.TestCaseGrouping"/>
  <testcase name="sampleTestOneMethodOne" time="0.001" classname="com.testng.training.SampleTestOne"/>
  <testcase name="sampleTestOneMethodTwo" time="0.001" classname="com.testng.training.SampleTestOne"/>
  <testcase name="testCaseOne" time="0.011" classname="com.testng.training.SoftAssertionExample">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Second hard assert failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Second hard assert failed expected [true] but found [false]
at com.testng.training.SoftAssertionExample.testCaseOne(SoftAssertionExample.java:17)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testCaseOne -->
  <testcase name="testCaseThree" time="0.005" classname="com.testng.training.SoftAssertionExample"/>
  <testcase name="testCasetwo" time="0.005" classname="com.testng.training.SoftAssertionExample">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Second soft assert failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Second soft assert failed expected [true] but found [false]
at com.testng.training.SoftAssertionExample.testCasetwo(SoftAssertionExample.java:28)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testCasetwo -->
  <testcase name="testTwo" time="0.0" classname="com.testng.training.SkippingExample">
    <ignored/>
  </testcase> <!-- testTwo -->
</testsuite> <!-- Sample Test Case for Package -->
